services:
  db:
    container_name: dating_db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails s -b '0.0.0.0' -p '3000'"
    stdin_open: true
    tty: true
    volumes:
      - .:/home/programmers_dating
    ports:
      - "3000:3000"
    depends_on:
      - db
  solid_queue:
    build: .
    command: bundle exec rake solid_queue:start
    volumes:
      - .:/home/programmers_dating
    depends_on:
      - db