default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: code_cupid_devel

test:
  <<: *default
  database: code_cupid_test

production:
  <<: *default
  database: code_cupid_prod
  username: code_cupid
  password: <%= ENV["CODE_CUPID_DATABASE_PASSWORD"] %>
