default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: code_cupid_devel

staging:
  <<: *default
  database: code_cupid_stg
  username: code_cupid_stg_user
  password: r1ZohMS2pP9n00lsib6uKF0i558dSJ3u

production:
  <<: *default
  database: code_cupid_prod
  username: code_cupid
  password: <%= ENV["CODE_CUPID_DATABASE_PASSWORD"] %>
