default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: programmers_dating_devel

test:
  <<: *default
  database: programmers_dating_test

production:
  <<: *default
  database: programmers_dating_prod
  username: programmers_dating
  password: <%= ENV["CONCURSEIRO_DATE_DATABASE_PASSWORD"] %>
